#!/usr/bin/env python
import sys
from unicodedata import east_asian_width as uwidth

padding = 0
if len(sys.argv) > 1:
    if sys.argv[1].isdecimal():
        padding = int(sys.argv[1])

data = []

try:
    while True:
        s = input().rstrip()
        width = sum(1+(uwidth(c) in "WF") for c in s)
        data.append((s, width))

except EOFError:
    pass

max_width = max(map(lambda x: x[1], data))
print('.{}.'.format('-'*(max_width+padding*2)))
for p in data:
    print('|{p}{d}{s}{p}|'.format(d=p[0], s=' '*(max_width-p[1]), p=' '*padding))

print("'{}'".format('-'*(max_width+padding*2)))

